name = "your-app-name"
compatibility_date = "2024-07-29"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[env.production.vars]
NEXTAUTH_URL = "https://your-domain.com"
NEXTAUTH_SECRET = "your-secret-key"
# 添加其他环境变量，记得给值加上双引号
